### PR TITLE
Will turn off modem if powered by battery after 30 minutes

### PR DESCRIPTION
**Pull request by CameronRP**
Modem will be powered off after 30 minutes if device is on battery.

### CODE REVIEW

**Review by mjs — COMMENTED** [review]
The code looks fine but how does this work for devices that have 3G coverage that are also on battery? Shouldn't they still be able to upload?

**Comment by CameronRP** [comment]
Yeah this should be improved in the future but for now they can upload the recordings in the 30 minute window.

**Comment by mjs** [comment]
As discussed on chat, I think it would be better to skip this and work on the modemd service instead.

**Comment by mjs** [comment]
We're replacing 3g-watchdog with modemd so this is no longer relevant

**Pull request closed without merging**
